workflows:
  flutter-apk-workflow:
    name: Flutter APK Builder
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      node: latest
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches/
        - ~/.gradle/wrapper/
    scripts:
      - name: تنظيف المشروع
        script: |
          flutter clean
      - name: تثبيت التبعيات
        script: |
          flutter pub get
      - name: إنشاء ملفات التوليد (إذا كان المشروع يستخدم build_runner)
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: إنشاء APK للإصدار
        script: |
          flutter build apk --release
      - name: إنشاء APK للإصدار (split per ABI)
        script: |
          flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
