workflows:
  flutter-apk-build:
    name: Flutter APK Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      java: 17

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Clean project
        script: |
          flutter clean

      - name: Build APK (release)
        script: |
          flutter build apk

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
